#!/usr/bin/env python
# -*- mode: python -*-

import sys

if not getattr(sys, 'frozen', False):
    import imp

    imp.load_module('py_natwest', *imp.find_module('lib'))

from py_natwest import Natwest


def main():
    nw = Natwest()
    nw.get_page()


if __name__ == '__main__':
    main()
